filme/urls.py
from django.urls import path,include, reverse_lazy
from .views import Homepage,Homefilmes,Detalhesfilme,Pesquisa,EditarPerfil,CriarConta,Favoritos
from django.contrib.auth import views as auth_view
from .registros import registrar_visualizacao,toggle_like_episodio,toggle_coracao_episodio,toggle_dislike_episodio,toggle_star_episodio,toggle_star_episodio_remove_favorites,toggle_filter_episodes

app_name = "filme"

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilme'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilmes'),

    path('pesquisa/', Pesquisa.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('criarconta/', CriarConta.as_view(), name='criarconta'),
    path('editarperfil/<int:pk>', EditarPerfil.as_view(), name='editarperfil'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name="editarperfil.html",
                                                                     success_url= reverse_lazy("filme:homefilme")), name='mudarsenha'),

    path('favoritos/', Favoritos.as_view(), name='favoritos'),

    path('toggle-filter-episodes/episodio/<int:pk>/', toggle_filter_episodes, name='toggle-filter-episodes'),

    path('registrar-visualizacao/episodio/<int:pk>/', registrar_visualizacao, name='registrar_visualizacao'),
    path('toggle-like/episodio/<int:pk>/', toggle_like_episodio, name='toggle_like'),
    path('toggle-dislike/episodio/<int:pk>/', toggle_dislike_episodio, name='toggle_dislike'),
    path('toggle-coracao/episodio/<int:pk>/', toggle_coracao_episodio, name='toggle_coracao'),
    path('toggle-star/episodio/<int:pk>/', toggle_star_episodio, name='toggle_star'),
    path('toggle-star-remove/episodio/<int:pk>/', toggle_star_episodio_remove_favorites, name='toggle_star_remove'),


]

flavideo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("filme.urls"), namespace="filme")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings

# Create your models here.


ANO_MINIMO = 2000
ANO_ATUAL = timezone.now().year

# Gera os anos como lista de tuplas para o choices
LISTA_ANOS = [(ano, str(ano)) for ano in range(ANO_MINIMO, ANO_ATUAL + 1)]

LISTA_CATEGORIAS = (
    ("Copa do Brasil", "Copa do Brasil"),
    ("Libertadores", "Libertadores"),
    ("Campeonato Estadual", "Campeonato Estadual"),
    ("Copa do Mundo de Clubes", "Copa do Mundo de Clubes"),
    ("Brasileirão", "Brasileirão"),
)

LISTA_FASES = (
    ("Fase de Grupos", "Fase de Grupos"),
    ("Oitavas de Final", "Oitavas de Final"),
    ("Quartas de Final", "Quartas de Final"),
    ("Semifinal", "Semifinal"),
    ("Final", "Final"),
)


class Filme(models.Model):
        ANO_MINIMO = 2000
        ANO_ATUAL = timezone.now().year


        titulo = models.CharField(max_length=100)
        thumb = models.ImageField(upload_to='thumb_filmes')
        descricao = models.TextField(max_length=1000)
        ano = models.IntegerField(choices=LISTA_ANOS,validators=[MinValueValidator(ANO_MINIMO),MaxValueValidator(ANO_ATUAL)])
        categoria = models.CharField(max_length=50,choices=LISTA_CATEGORIAS,default="Outros")
        visualizacoes = models.IntegerField(default=0)
        data_criacao = models.DateTimeField(default=timezone.now)
        campeao = models.BooleanField(default=False)
        def __str__(self):
            return self.titulo


class Episodio(models.Model):
    # --- Campos do Modelo ---
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_episodios', null=True, blank=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    link = models.URLField()
    descricao = models.TextField(max_length=1000)
    fases = models.CharField(max_length=50, choices=LISTA_FASES, default="Outros")
    visualizacoes = models.IntegerField(default=0)

    # --- Relacionamentos ManyToMany ---
    usuarios_que_curtiram = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="episodios_curtidos", blank=True)
    usuarios_dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="episodios_dislike", blank=True)
    usuarios_que_amaram = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="episodios_amados", blank=True)

    # --- Propriedades Calculadas (FORMA CORRETA) ---
    @property
    def total_likes(self):
        return self.usuarios_que_curtiram.count()

    @property
    def total_dislikes(self):
        return self.usuarios_dislikes.count()

    @property
    def total_coracao(self):
        return self.usuarios_que_amaram.count()

    def __str__(self):
        return f"{self.filme.titulo} - {self.titulo}"


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField(
        "Filme",
        related_name="usuarios_que_viram"
    )
    episodios_favoritos = models.ManyToManyField(
        "Episodio",
        related_name="usuarios_que_favoritaram" # Nome técnico para o acesso reverso
    )

    @property
    def total_episodios_favoritos(self):
        return self.episodios_favoritos.count()

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField()


class CriarContaForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme,Usuario,Episodio
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CriarContaForm,FormHomepage
from django.shortcuts import render, get_object_or_404
# Create your views here.

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("filme:homefilme")
        else:
            return super().get(request, *args, **kwargs) #redireciona para a homepage

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse("filme:login")
        else:
            return reverse("filme:criarconta")

class Homefilmes(LoginRequiredMixin,ListView):
    template_name = "homefilmes.html"
    model = Filme

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add the user's viewed movies to the context
        context["filmes_vistos_do_usuario"] = self.request.user.filmes_vistos.all()
        return context

class Detalhesfilme(LoginRequiredMixin,DetailView):
    template_name = "detalhes_filmes.html"
    model = Filme

    def get(self, request, *args, **kwargs):   #sempre quando o usuario faz um metodo get na pagina de url (.../filmes/n (n = 1 ou 2 ou 3...)) ira contar essa requisicao e depois vai somar a visualizacao
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs) #redireciona para a url final

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)


        current_movie = self.get_object()

        # Linhas originais: Lógica para buscar filmes relacionados
        filmes_relacionados = self.model.objects.filter(categoria=current_movie.categoria).exclude(pk=current_movie.pk)[
                              0:4]
        context["filmes_relacionados"] = filmes_relacionados


        fases_unicas = Episodio.objects.filter(filme=current_movie).values_list('fases', flat=True).distinct().order_by('fases')
        context['fases_unicas'] = fases_unicas

        return context

class Pesquisa(LoginRequiredMixin,ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):
        get_pesquisa = self.request.GET.get("query")
        if get_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=get_pesquisa)
            return object_list
        else:
            return None

class EditarPerfil(LoginRequiredMixin,UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse("filme:homefilmes")

class CriarConta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("filme:login")

class Favoritos(ListView):
    template_name = "favoritos.html"
    model = Usuario
    context_object_name = 'lista_episodios_favoritos'


    def get_queryset(self):
        return self.request.user.episodios_favoritos.all()

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/editarperfil.css' %}">
{% endblock %}


{% block content %}
<main class="main-content login-page background-image-container">
    <div class="overlay" aria-hidden="true"></div>

    <div class="form-container logout-width"> {# Using logout-width for max-width: 672px as per original intent #}
        <div class="form-card">
            <div class="card-header">
                <h1 class="card-title">
                    Crie sua Conta
                </h1>
                <p class="card-subtitle">Junte-se à Nação e aproveite o melhor conteúdo.</p>
            </div>

            <form method="post" class="auth-form">
                {% csrf_token %}

                <fieldset>
                    {{ form|crispy }}
                </fieldset>

                <div>
                    <button class="btn-primary" type="submit">
                        Criar Conta
                    </button>
                </div>
            </form>

            <div class="card-bottom-text">
                <span>Já tem uma conta?</span>
                <a href="{% url 'filme:login' %}" class="card-bottom-link">
                    Faça o login
                </a>
            </div>
        </div>
    </div>
</main>

<footer class="app-footer">
    <div class="footer-content-wrapper">
        <div class="footer-links">
            <p class="footer-text">© {% now "Y" %} FlaTV. Todos os direitos reservados.</p>
            <p class="footer-text-secondary">Uma plataforma para torcedores.</p>
            <p class="footer-text-tech">Feito com Python (Django) & TailwindCSS</p>
        </div>
    </div>
</footer>
{% endblock %}

filme/templates/detalhes_filmes.html
{% extends 'base.html' %}
{% load static %}

{% block body_class %}pagina-inicial{% endblock %}

{% block titulo %}
    {{ object.titulo }}
{% endblock %}]

{% block head %}
    <link rel="stylesheet" href="{% static 'css/detalhes_filme.css' %}">
{% endblock %}


{% block content %}
    <main class="main-container">


        <!-- TITULO -->

        <section class="hero-section" style="background-image: url('{{ object.thumb.url}}');">
            <div class="hero-content">
                <h2 class="hero-title">{{ object.titulo}}</h2>
                </p>
                <p class="description-text"> {{ object.descricao }} <br>
                    <span class="views-count">Visualizações : {{ object.visualizacoes }}</span>
                </p>
                <div class="hero-actions">
                    <a href="/">
                        <button class="play-button">
                            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="currentColor">
                                <path d="M0 0h24v24H0V0z" fill="none"/>
                                <path d="M8 5v14l11-7L8 5z"/>
                            </svg>
                            <span class="play-button-text">Play</span>
                        </button>
                    </a>
                </div>
            </div>
        </section>

        <!-- JOGOS -->

        <section class="content-section">
        <div class="content-wrapper">
            <div class="episodes-container">
                <div class="section-title-container">

                    <h2 class="section-title">Jogos</h2>
                    <div class="select-box">
                            <div class="select-container">

                                <select id="rodada" name="rodada">
                                    <option value="">- Todos -</option>

                                    {% for fase in fases_unicas %}

                                    <option value="{{ fase }}">{{ fase }}</option>

                                    {% endfor %}
                                </select>
                                <ion-icon name="caret-down-outline" class="arrow_down"></ion-icon>
                            </div>
                    </div>
                    </div>
                </div>

                <div class="episodes-list">
                    {% for episodio in object.episodios.all %}

                    <div class="episode-card" data-fase="{{ episodio.fases }}">

                        <div class="thumbnail-wrapper"
                             data-video-src="{% if episodio.video %}{{ episodio.video.url }}{% endif %}"
                             data-episode-id="{{ episodio.id }}">

                            <img src="{{ episodio.thumb.url }}" alt="{{ episodio.titulo }}" class="episode-thumbnail">
                            <div class="button-play">▶</div>
                        </div>

                        <div class="episode-card-content">
                            <h3 class="episode-title">{{ episodio.titulo }} </h3>
                            <p class="episode-description">{{ episodio.fases }}</p>
                            <h4 class="count_views">{{ episodio.visualizacoes }} Visualizacoes </h4>

                            <div class="video-buttons">
                                {% csrf_token %}
                                <button class="btn-like {% if request.user in episodio.usuarios_que_curtiram.all %}ativo{% endif %}"
                                        data-episode-id="{{ episodio.id }}"
                                        aria-label="Curtir">

                                    <i class="{% if request.user in episodio.usuarios_que_curtiram.all %}fa-solid{% else %}fa-regular{% endif %} fa-thumbs-up"></i>
                                </button>
                                <span id="like-count-{{ episodio.id }}">{{ episodio.total_likes }}</span>


                                <button class="btn-dislike {% if request.user in episodio.usuarios_dislikes.all %}ativo{% endif %}"
                                        data-episode-id="{{ episodio.id }}"
                                        aria-label="Não Curtir">
                                    <i class="{% if request.user in episodio.usuarios_dislikes.all %}fa-solid{% else %}fa-regular{% endif %} fa-thumbs-down"></i>
                                </button>

                                <button class="btn-heart {% if request.user in episodio.usuarios_que_amaram.all %}ativo{% endif %}"
                                    data-episode-id="{{ episodio.id }}"
                                    aria-label="Heart">

                                    <i class="{% if request.user in episodio.usuarios_que_amaram.all %}fa-solid{% else %}fa-regular{% endif %} fa-heart"></i>
                                </button>
                                <span id="heart-count-{{ episodio.id }}">{{ episodio.total_coracao }}</span>

                                <button class="btn-star {% if episodio in request.user.episodios_favoritos.all %}ativo{% endif %}"
                                        data-episode-id="{{ episodio.id }}"
                                        aria-label="Star">
                                    <i class="{% if episodio in request.user.episodios_favoritos.all %}fa-solid{% else %}fa-regular{% endif %} fa-star"></i>
                                </button>
                            </div>


                            {% if episodio.video %}
                            <video id="video-{{ episodio.id }}" class="video-player w-full rounded mt-4"
                                   style="display: none;" controls> <source src="{{ episodio.video.url }}" type="video/mp4">
                            </video>
                            {% else %}
                            <p class="text-gray-500 italic">Vídeo não disponível.</p>
                            {% endif %}

                        </div>

                    </div>
                    {% empty %}
                    {# Adicionei a tag 'empty' que estava faltando na sua versão, para o caso de não haver episódios #}
                    <p>Este filme ainda não possui episódios.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        </section>

        <!-- RELACIONADOS -->
         {% if filmes_relacionados|length > 0 %}
        <section class="content-section">
        <div class="content-wrapper">
            <h2 class="related-title">Relacionados</h2>
            <div class="related-movies-grid">
                {% for filme in filmes_relacionados %}
                <div class="movie-card">
                    <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                        <img src="{{ filme.thumb.url }}" alt="Filme Relacionado" class="movie-card-image">
                        <h3 class="movie-card-title">{{ filme.titulo }}</h3>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
         {% endif %}
        <form style="display: none;">{% csrf_token %}</form>
    </main>


    <div id="player-overlay" class="player-overlay-container">
    <div class="meu-player-container">
        <video id="meu-video" src=""></video>

        <div class="meu-player-controls">
            <div class="controls-left">
                <button id="rewind-btn" class="control-btn" aria-label="Retroceder 10s">
                    <i class="fa-solid fa-rotate-left"></i>
                </button>
                <button id="play-pause-btn" class="control-btn" aria-label="Play/Pause">
                    <i class="fa-solid fa-play"></i>
                </button>
                <button id="forward-btn" class="control-btn" aria-label="Avançar 10s">
                    <i class="fa-solid fa-rotate-right"></i>
                </button>
                <div class="volume-container">
                    <button id="mute-btn" class="control-btn" aria-label="Mudo">
                        <i class="fa-solid fa-volume-high"></i>
                    </button>
                    <input type="range" id="volume-bar" class="volume-bar" value="1" min="0" max="1" step="0.01" />
                </div>
            </div>

            <div class="controls-right">
                <div class="time-display">
                    <span id="current-time">00:00</span> / <span id="duration">00:00</span>
                </div>
                <button id="fullscreen-btn" class="control-btn" aria-label="Tela Cheia">
                    <i class="fa-solid fa-expand"></i>
                </button>
            </div>
        </div>

        <input type="range" id="progress-bar" class="progress-bar" value="0" min="0" max="100" step="0.1" />
    </div>
    <button id="close-player-btn" class="close-player-btn">&times;</button>
</div>
{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/editarperfil.css' %}">
{% endblock %}


{% block content %}


<main class="main-content edit-profile-page background-image-container">
    <div class="overlay"></div>

    <div class="form-container edit-profile-width">
        <div class="form-card">
            <div class="card-header">
                <h2 class="card-title">Olá, {{ user.first_name }} {{ user.last_name }}</h2>
            </div>

            <form method="post" class="auth-form">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="form-legend">Edite os campos abaixo para editar seu perfil</legend>
                    {{ form|crispy }}
                </fieldset>
                <div> {# Retained this div for original css structure, but can be merged if not critical #}
                    <button class="btn-primary" type="submit">Editar Perfil</button>
                </div>
            </form>

            <div class="card-bottom-text">
                <span>
                    <a href="{% url 'filme:mudarsenha' %}" class="card-bottom-link">Quer mudar sua senha?</a>
                </span>
            </div>
        </div>
    </div>
</main>

<footer class="app-footer">
    <div class="footer-content-wrapper">
        <div class="footer-links">
            <p class="footer-text">© {% now "Y" %} FlaTV. Todos os direitos reservados.</p>
            <p class="footer-text-secondary">Uma plataforma para torcedores.</p>
            <p class="footer-text-tech">Feito com Python (Django) & CSS Puro</p>
        </div>
    </div>
</footer>
{% endblock %}

filme/templates/favoritos.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Favoritos
{% endblock %}]

{% block head %}
    <link rel="stylesheet" href="{% static 'css/favoritos.css' %}">
{% endblock %}

{% block content %}
<main class="main-container">
    <section class="results-section">
        <div class="results-container">
            <h2 class="results-title">Meus Jogos Favoritos</h2>

            {% if lista_episodios_favoritos %}
                <div class="movie-list">
                    {% for episodio in lista_episodios_favoritos %}

                        <div class="movie-card">

                            <div class="thumbnail-wrapper"
                                 data-video-src="{% if episodio.video %}{{ episodio.video.url }}{% endif %}"
                                 data-episode-id="{{ episodio.id }}">

                                <img src="{{ episodio.thumb.url }}" class="movie-thumbnail" alt="{{ episodio.titulo }}">
                                <div class="button-play">▶</div>

                        </div>

                            <div class="card-content">
                                <h3 class="card-title">{{ episodio.titulo }}</h3>
                                <div class="card-category-star">
                                    <a href="{% url 'filme:detalhesfilmes' episodio.filme.pk %}">
                                        <p class="card-category">{{ episodio.filme.categoria }} - {{ episodio.filme.ano }}</p>
                                    </a>
                                    <button class="btn-star ativo"
                                                data-episode-id="{{ episodio.id }}"
                                                aria-label="Star">
                                            <i class="fa-solid fa-star"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        {% if episodio.video %}
                            <video id="video-{{ episodio.id }}" class="video-player w-full rounded mt-4"
                                   style="display: none;" controls> <source src="{{ episodio.video.url }}" type="video/mp4">
                            </video>
                        {% else %}
                            <p class="text-gray-500 italic">Vídeo não disponível.</p>
                        {% endif %}

                    {% endfor %}

                </div>
            {% else %}
                {# Adicionamos uma mensagem para quando a lista estiver vazia #}
                <p style="color: #ccc; text-align: center; margin-top: 40px;">Você ainda não favoritou nenhum jogo.</p>
            {% endif %}
        </div>
        <div id="player-overlay" class="player-overlay-container">
    <div class="meu-player-container">
        <video id="meu-video" src=""></video>

        <div class="meu-player-controls">
            <div class="controls-left">
                <button id="rewind-btn" class="control-btn" aria-label="Retroceder 10s">
                    <i class="fa-solid fa-rotate-left"></i>
                </button>
                <button id="play-pause-btn" class="control-btn" aria-label="Play/Pause">
                    <i class="fa-solid fa-play"></i>
                </button>
                <button id="forward-btn" class="control-btn" aria-label="Avançar 10s">
                    <i class="fa-solid fa-rotate-right"></i>
                </button>
                <div class="volume-container">
                    <button id="mute-btn" class="control-btn" aria-label="Mudo">
                        <i class="fa-solid fa-volume-high"></i>
                    </button>
                    <input type="range" id="volume-bar" class="volume-bar" value="1" min="0" max="1" step="0.01" />
                </div>
            </div>

            <div class="controls-right">
                <div class="time-display">
                    <span id="current-time">00:00</span> / <span id="duration">00:00</span>
                </div>
                <button id="fullscreen-btn" class="control-btn" aria-label="Tela Cheia">
                    <i class="fa-solid fa-expand"></i>
                </button>
            </div>
        </div>

        <input type="range" id="progress-bar" class="progress-bar" value="0" min="0" max="100" step="0.1" />
    </div>
    <button id="close-player-btn" class="close-player-btn">&times;</button>
</div>

    </section>
</main>
{% endblock %}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Login
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/editarperfil.css' %}">
{% endblock %}

{% block content %}
<main class="main-content login-page background-image-container">
    <div class="overlay" aria-hidden="true"></div>

    <div class="form-container">
        <div class="form-card">
            <div class="card-header">
                <h1 class="card-title">
                    Acesse sua Conta
                </h1>
                <p class="card-subtitle">Bem-vindo de volta, Nação!</p>
            </div>

            <form method="post" class="auth-form">
                {% csrf_token %}
                <fieldset>
                    {{ form|crispy }}
                </fieldset>
                <div>
                    <button class="btn-primary" type="submit">
                        Fazer Login
                    </button>
                </div>
            </form>

            <div class="card-bottom-text">
                <span>Não tem uma conta?</span>
                <a href="{% url 'filme:criarconta' %}" class="card-bottom-link">
                    Crie uma agora
                </a>
            </div>
        </div>
    </div>
</main>
<footer class="app-footer">
    <div class="footer-content-wrapper">
        <div class="footer-links">
            <p class="footer-text">© {% now "Y" %} FlaTV. Todos os direitos reservados.</p>
            <p class="footer-text-secondary">Uma plataforma para torcedores.</p>
            <p class="footer-text-tech">Feito para Python (Django) & TailwindCSS</p>
        </div>
    </div>
</footer>
{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{% static 'css/editarperfil.css' %}">
{% endblock %}


{% block content %}
<main class="main-content logout-page background-image-container">
    <div class="overlay" aria-hidden="true"></div>

    <div class="form-container logout-width">
        <div class="form-card logout-card">

            <div class="card-header">
                <h1 class="card-title logout-title">
                    Você saiu da sua conta
                </h1>
                <p class="card-description">
                    Sessão encerrada com segurança. Esperamos ver você novamente em breve!
                </p>
            </div>

            <div class="button-group">
                <a href="{% url 'filme:login' %}" class="btn-primary">
                    Fazer Login
                </a>
                <a href="{% url 'filme:criarconta' %}" class="btn-secondary">
                    Criar uma Conta
                </a>
            </div>
        </div>
    </div>
</main>

<footer class="app-footer">
    <div class="footer-content-wrapper">
        <div class="footer-links">
            <p class="footer-text">© {% now "Y" %} FlaTV. Todos os direitos reservados.</p>
            <p class="footer-text-secondary">Uma plataforma para torcedores.</p>
            <p class="footer-text-tech">Feito com Python (Django) & TailwindCSS</p>
        </div>
    </div>
</footer>
{% endblock %}

filme/templates/pesquisa.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Pesquisa de Filme
{% endblock %}]

{% block head %}
    <link rel="stylesheet" href="{% static 'css/pesquisa.css' %}">
{% endblock %}

{% block content %}
<main class="main-container">


    <section class="results-section">
        <div class="results-container">
            <h2 class="results-title">Resultados da Busca</h2>
            <div class="movie-list">
                {% for filme in object_list %}
                    <a href="{% url 'filme:detalhesfilmes' filme.pk %}" class="movie-card">
                        <img src="{{ filme.thumb.url }}" class="movie-thumbnail" alt="{{ filme.titulo }}">

                        <div class="card-content">
                            <p class="card-category">{{ filme.categoria }}</p>
                            <h3 class="card-title">{{ filme.titulo }}</h3>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>


</main>
{% endblock %}