filme/urls.py
from django.urls import path,include, reverse_lazy
from .views import Homepage,Homefilmes,Detalhesfilme,Pesquisa,EditarPerfil,CriarConta,Favoritos
from django.contrib.auth import views as auth_view
from .registros import registrar_visualizacao,toggle_like_episodio,toggle_coracao_episodio,toggle_dislike_episodio,toggle_star_episodio,toggle_star_episodio_remove_favorites,toggle_filter_episodes

app_name = "filme"

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilme'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilmes'),

    path('pesquisa/', Pesquisa.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('criarconta/', CriarConta.as_view(), name='criarconta'),
    path('editarperfil/<int:pk>', EditarPerfil.as_view(), name='editarperfil'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name="editarperfil.html",
                                                                     success_url= reverse_lazy("filme:homefilme")), name='mudarsenha'),

    path('favoritos/', Favoritos.as_view(), name='favoritos'),

    path('toggle-filter-episodes/episodio/<int:pk>/', toggle_filter_episodes, name='toggle-filter-episodes'),

    path('registrar-visualizacao/episodio/<int:pk>/', registrar_visualizacao, name='registrar_visualizacao'),
    path('toggle-like/episodio/<int:pk>/', toggle_like_episodio, name='toggle_like'),
    path('toggle-dislike/episodio/<int:pk>/', toggle_dislike_episodio, name='toggle_dislike'),
    path('toggle-coracao/episodio/<int:pk>/', toggle_coracao_episodio, name='toggle_coracao'),
    path('toggle-star/episodio/<int:pk>/', toggle_star_episodio, name='toggle_star'),
    path('toggle-star-remove/episodio/<int:pk>/', toggle_star_episodio_remove_favorites, name='toggle_star_remove'),


]

flavideo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("filme.urls"), namespace="filme")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block titulo %}
      {% endblock %}
    </title>
    {% load static %}

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet"/>

    <link rel="icon" type="image/x-icon" href="{% static 'imagens/favicon.ico' %}">

    {% block head %}
    {% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/detalhes_filmes.js' %}"></script>
    <script src="{% static 'js/homefilmes.js' %}"></script>
    <script src="{% static 'js/favoritos.js' %}"></script>
</body>
</html>

templates/navbar.html
{% load static %}



{% block head %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}

<nav>
<header class="main-header">
  <div class="header-logo-container">
    <a href="/">
      <img
         src="{% static 'imagens/FlaVideo_oficial.png' %}"
        alt="FlaVideo Logo"
        class="flacvideo-logo"
      />
    </a>
  </div>

  <div class="header-nav-container">
    {% if user.is_authenticated %}
    <div class="search-bar-wrapper">
      <form method="get" action="{% url 'filme:pesquisafilme' %}">
        <div class="search-input-container">
          <svg
            class="search-icon"
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
          </svg>
          <input
            type="text"
            placeholder="Pesquisar vídeos..."
            class="search-input"
            name="query"
            value="{{ request.GET.query }}"
          />
          <input type="submit" value="" class="hidden-submit">
        </div>
      </form>
    </div>


        {% if user.is_authenticated %}
            {# Primeiro, salvamos a URL da página de favoritos em uma variável para facilitar a comparação #}
            {% url 'filme:favoritos' as favoritos_url %}

            {# Agora, verificamos se o caminho da página atual (request.path) é DIFERENTE da URL de favoritos #}
            {% if request.path != favoritos_url %}
                <div class="favorites-link-wrapper">
                  <a href="{{ favoritos_url }}" title="Meus Favoritos">
                    <button class="btn-header-favorites">
                        <i class="fa-solid fa-star"></i>
                    </button>
                  </a>
                </div>
            {% endif %}
        {% endif %}

    <form method="post" action="{% url 'filme:logout' %}">
        {% csrf_token %}
        <button type="submit" class="login-button">Sair</button>
      </form>
    <a href="{% url 'filme:editarperfil' request.user.pk %}">
        <button type="button" class="profile-button">
          Perfil
        </button>
      </a>
    {% else %}
      <a href="{% url 'filme:login'%}">
        <button type="button" class="login-button">
          Login
        </button>
      </a>
     {% endif %}

  </div>
</header>
</nav>